-- Esquema de la base de datos de Kupi-dev (proyecto de Supabase propio, separado del
-- Kupi del hackathon). Se corre una sola vez en: Supabase → SQL Editor → New query.
--
-- Diferencias con el esquema del hackathon:
--   * user_favorites y price_snapshots guardan la ubicación (lat, lng): el envío y la
--     cuota dependen de dónde está cada usuario, y Kupi funciona en todo el país.
--   * restaurants.city ya no es 'culiacan' por defecto.
--   * Índices para las consultas frecuentes e ids únicos de tienda (sin duplicados).
--   * RLS activado: el backend usa la secret key (no le aplica RLS); con la llave pública
--     solo se pueden leer los cupones.

create table if not exists restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  rappi_store_id text,
  ubereats_store_id text,
  cuisine text default '',
  image_url text default '',
  city text default '',
  match_confidence text default 'manual',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create unique index if not exists restaurants_rappi_store_id_key on restaurants (rappi_store_id) where rappi_store_id is not null;
create unique index if not exists restaurants_ubereats_store_id_key on restaurants (ubereats_store_id) where ubereats_store_id is not null;

create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  restaurant_name text not null,
  product_name text not null,
  rappi_product_id text,
  ubereats_product_id text,
  rappi_store_id text,
  ubereats_store_id text,
  image_url text default '',
  lat double precision,
  lng double precision,
  created_at timestamptz default now()
);
create index if not exists user_favorites_user_id_idx on user_favorites (user_id);

create table if not exists price_snapshots (
  id bigint generated by default as identity primary key,
  rappi_product_id text,
  ubereats_product_id text,
  product_name text not null,
  platform text not null,
  product_price numeric not null,
  delivery_fee numeric,
  service_fee numeric,
  total numeric not null,
  rappi_store_id text,
  ubereats_store_id text,
  lat double precision,
  lng double precision,
  sampled_at timestamptz default now()
);
create index if not exists price_snapshots_rappi_idx on price_snapshots (rappi_product_id, sampled_at);
create index if not exists price_snapshots_ue_idx on price_snapshots (ubereats_product_id, sampled_at);

create table if not exists price_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  favorite_id bigint not null references user_favorites (id) on delete cascade,
  alert_type text not null default 'price_drop',
  threshold_pct numeric default 5.0,
  is_active boolean default true,
  last_notified_at timestamptz,
  created_at timestamptz default now()
);
create index if not exists price_alerts_user_id_idx on price_alerts (user_id);
create index if not exists price_alerts_favorite_id_idx on price_alerts (favorite_id);

create table if not exists alert_notifications (
  id bigint generated by default as identity primary key,
  alert_id bigint references price_alerts (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  message text not null,
  channel text default 'email',
  sent_at timestamptz default now()
);

create table if not exists coupons (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  restaurant_id text[] not null,
  restaurant_name text not null,
  platform text not null,
  description text not null,
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  deep_link text
);

alter table restaurants enable row level security;
alter table user_favorites enable row level security;
alter table price_snapshots enable row level security;
alter table price_alerts enable row level security;
alter table alert_notifications enable row level security;
alter table coupons enable row level security;

drop policy if exists "Cupones visibles para todos" on coupons;
create policy "Cupones visibles para todos" on coupons for select to anon, authenticated using (true);

-- Imágenes de restaurantes (CDN de Supabase Storage)
insert into storage.buckets (id, name, public)
values ('restaurant-images', 'restaurant-images', true)
on conflict (id) do nothing;
